<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 18 Sep 2015 12:31:43 +0200
 */

$conf['disableactions'] = 'register';
$conf['subscribers'] = 1;
$conf['notify'] = '594940274@qq.com';
$conf['mailfrom'] = 'service1@manyule.com';
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['plugin']['indexmenu']['skip_index'] = '/^(discussion|playground)\\$/i';
$conf['plugin']['indexmenu']['replace_idx'] = 'static';
$conf['plugin']['indexmenu']['replace_idx_theme'] = 'backup';
$conf['plugin']['swiftmail']['smtp_host'] = 'smtp.exmail.qq.com';
$conf['plugin']['swiftmail']['smtp_port'] = 465;
$conf['plugin']['swiftmail']['smtp_ssl'] = '4';
$conf['plugin']['swiftmail']['auth_user'] = 'service1@manyule.com';
$conf['plugin']['swiftmail']['auth_pass'] = '9PqXtiP2MHLEBnBk';
$conf['plugin']['swiftmail']['debug'] = 1;

// end auto-generated content
